export interface MockPost {
  id: number;
  username: string;
  content: string;
  timestamp: string;
  likes: number;
  comments: number;
  avatarUrl: string;
}

export const MOCK_POSTS: MockPost[] = [
  {
    id: 1,
    username: "JohnDoe",
    content: "Ayoooooo",
    timestamp: "2h ago",
    likes: 42,
    comments: 7,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 2,
    username: "JaneDoe",
    content: "This app is lit",
    timestamp: "4h ago",
    likes: 28,
    comments: 12,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 3,
    username: "TechGuru",
    content: "Just deployed my first smart contract! Web3 is the future 🚀",
    timestamp: "5h ago",
    likes: 156,
    comments: 23,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 4,
    username: "CryptoQueen",
    content: "Market's looking bullish today! 📈 Who's holding?",
    timestamp: "6h ago",
    likes: 89,
    comments: 34,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 5,
    username: "DevLife",
    content:
      "4 cups of coffee and still debugging the same issue. Send help! ☕️",
    timestamp: "7h ago",
    likes: 245,
    comments: 45,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 6,
    username: "ArtisticSoul",
    content: "Just finished my latest digital artwork! What do you think? 🎨",
    timestamp: "8h ago",
    likes: 178,
    comments: 28,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 7,
    username: "FoodieExplorer",
    content:
      "Found this amazing ramen spot downtown! The broth is incredible 🍜",
    timestamp: "9h ago",
    likes: 134,
    comments: 19,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 8,
    username: "StartupFounder",
    content: "Big announcement coming soon! Stay tuned 👀",
    timestamp: "10h ago",
    likes: 567,
    comments: 89,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 9,
    username: "TravelBug",
    content: "Just booked my tickets to Bali! Any recommendations? ✈️",
    timestamp: "11h ago",
    likes: 223,
    comments: 56,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 10,
    username: "MusicProducer",
    content: "New track dropping this weekend! It's my best work yet 🎵",
    timestamp: "12h ago",
    likes: 445,
    comments: 67,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 11,
    username: "GamingPro",
    content: "Just hit Diamond rank! The grind was worth it 🎮",
    timestamp: "13h ago",
    likes: 312,
    comments: 45,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 12,
    username: "BookWorm",
    content:
      "Finally started reading 'Dune'. Can't believe I waited this long! 📚",
    timestamp: "14h ago",
    likes: 178,
    comments: 34,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 13,
    username: "FitnessFreak",
    content: "New PR on deadlifts today! 💪 Feeling unstoppable",
    timestamp: "15h ago",
    likes: 289,
    comments: 42,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 14,
    username: "ChefExtraordinaire",
    content: "Experimenting with fusion cuisine. Sushi burrito anyone? 🍣🌯",
    timestamp: "16h ago",
    likes: 234,
    comments: 38,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 15,
    username: "PlantParent",
    content:
      "My monstera just sprouted a new leaf! Plant people will understand 🌱",
    timestamp: "17h ago",
    likes: 156,
    comments: 23,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 16,
    username: "JohnDoe",
    content: "Ayoooooo",
    timestamp: "2h ago",
    likes: 42,
    comments: 7,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 17,
    username: "JaneDoe",
    content: "This app is lit",
    timestamp: "4h ago",
    likes: 28,
    comments: 12,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 18,
    username: "TechGuru",
    content: "Just deployed my first smart contract! Web3 is the future 🚀",
    timestamp: "5h ago",
    likes: 156,
    comments: 23,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 19,
    username: "CryptoQueen",
    content: "Market's looking bullish today! 📈 Who's holding?",
    timestamp: "6h ago",
    likes: 89,
    comments: 34,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 20,
    username: "DevLife",
    content:
      "4 cups of coffee and still debugging the same issue. Send help! ☕️",
    timestamp: "7h ago",
    likes: 245,
    comments: 45,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 21,
    username: "ArtisticSoul",
    content: "Just finished my latest digital artwork! What do you think? 🎨",
    timestamp: "8h ago",
    likes: 178,
    comments: 28,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 22,
    username: "FoodieExplorer",
    content:
      "Found this amazing ramen spot downtown! The broth is incredible 🍜",
    timestamp: "9h ago",
    likes: 134,
    comments: 19,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 23,
    username: "StartupFounder",
    content: "Big announcement coming soon! Stay tuned 👀",
    timestamp: "10h ago",
    likes: 567,
    comments: 89,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 24,
    username: "TravelBug",
    content: "Just booked my tickets to Bali! Any recommendations? ✈️",
    timestamp: "11h ago",
    likes: 223,
    comments: 56,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 25,
    username: "MusicProducer",
    content: "New track dropping this weekend! It's my best work yet 🎵",
    timestamp: "12h ago",
    likes: 445,
    comments: 67,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 26,
    username: "GamingPro",
    content: "Just hit Diamond rank! The grind was worth it 🎮",
    timestamp: "13h ago",
    likes: 312,
    comments: 45,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 27,
    username: "BookWorm",
    content:
      "Finally started reading 'Dune'. Can't believe I waited this long! 📚",
    timestamp: "14h ago",
    likes: 178,
    comments: 34,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 28,
    username: "FitnessFreak",
    content: "New PR on deadlifts today! 💪 Feeling unstoppable",
    timestamp: "15h ago",
    likes: 289,
    comments: 42,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 29,
    username: "ChefExtraordinaire",
    content: "Experimenting with fusion cuisine. Sushi burrito anyone? 🍣🌯",
    timestamp: "16h ago",
    likes: 234,
    comments: 38,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 30,
    username: "PlantParent",
    content:
      "My monstera just sprouted a new leaf! Plant people will understand 🌱",
    timestamp: "17h ago",
    likes: 156,
    comments: 23,
    avatarUrl: "/stock-avatar.jpg",
  },
  {
    id: 31,
    username: "NightOwl",
    content:
      "3 AM thoughts: Why do we park in driveways but drive on parkways? 🤔",
    timestamp: "2d ago",
    likes: 678,
    comments: 145,
    avatarUrl: "/stock-avatar.jpg",
  },
];
